language: php 
php: 
 - 5.3

env:
 - DB=MYSQL CORE_RELEASE=2.4
 - DB=PGSQL CORE_RELEASE=2.4

before_script:
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - vendor/bin/phpunit cms/tests

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging

notifications:
  irc:
    channels:
     - "irc.freenode.org#silverstripe"