SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
SilverStripe\Control\Controller:
  extensions:
    - SilverStripe\CMS\Controllers\ErrorPageControllerExtension
SilverStripe\Forms\Form:
  extensions:
    - SilverStripe\CMS\Controllers\ErrorPageControllerExtension
SilverStripe\Assets\File:
  extensions:
    - SilverStripe\CMS\Controllers\ErrorPageFileExtension
    - SilverStripe\CMS\Model\SiteTreeFileExtension
